//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
