//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistributionApp.DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class ReceiveGood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceiveGood()
        {
            this.ReceiveGoodDetails = new HashSet<ReceiveGoodDetail>();
        }
    
        public int ReceiveGoodId { get; set; }
        public string TruckNumber { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string DocumentNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiveGoodDetail> ReceiveGoodDetails { get; set; }

        // The following property is used for showing parent and child relationship
        public ObservableCollection <ReceiveGoodDetail> ShowReceiveGoodDetails { get; set; }
    }
}
